description: Base system packages

# Use the flat syntax as seen in your other files.
# We point to the global 'scripts/' folder relative to where you run dcli (repo root).
post_install_hook: ""
hooks_behavior: skip
packages:
  # Essential base system
  - base
  - base-devel

  # Firmware
  - linux-firmware
  - linux-firmware-intel
  - intel-ucode
  - xone-dongle-firmware
  - xone-dkms
  #- limine-mkinitcpio-hook
  #- limine-entry-tool
  - limine-snapper-sync

  # dcli dependencies
  - paru
  - yay-bin
  - fzf
  - snapper


  # File managers
  - nemo

  # Theming
  - python-pywal

  # Core CLI utilities
  - wget
  - curl
  - unzip
  - usbutils
  - nvtop
  - imv
  - jaq
  - lvm2
  - eza
  - bat
  - ripgrep
  - fd
  - brightnessctl

  # Utilities & compression
  - bind-tools
  - tealdeer
  - xdg-utils
  - xdg-user-dirs
  - shared-mime-info
  - perl-file-mimeinfo
  - ueberzugpp
  - dosfstools
  - evtest
   
  # System GUI applications
  - network-manager-applet
  - networkmanager
  - networkmanager-openvpn
  - nftables

  # Audio system packages
  - pipewire
  - wireplumber
  - cava
  - libsixel
  - alsa-utils
  - bluez-tools
  - bluez
  - bluez-utils
  - pipewire-audio
  - pipewire-alsa
  - pipewire-pulse
  - pipewire-jack
  - rtkit
  - blueman
  - noise-suppression-for-voice
  - rnnoise

  # System monitoring & management
  - lm_sensors
  - gammastep
  - wlsunset
  - geoclue
  - mkinitcpio
  - mkinitcpio-firmware
  - mkinitcpio-busybox
  - cachyos-ananicy-rules
  - ananicy-cpp
  - busybox
  - upower
  - tuned
  - thermald
  - fwupd
  - earlyoom

  # System utilities & tools
  - ffmpeg

  # File system tools
  - btrfs-progs
  - f2fs-tools
  - btrfs-assistant-git
  - compsize
  - virtiofsd
  - duperemove
  - fuseiso
  - fuse3
  - fuse2
  - libappimage
  - gvfs
  - avfs
  - btrfs-heatmap
  - disorderfs

  # XanMod Edge Kernel
  - linux-xanmod-edge-linux-bin-x64v3
  - linux-xanmod-edge-linux-headers-bin-x64v3

  # Screenshot & recording
  #- wl-screenrec
  - swappy

  # Network & security
  - nmap
  - wireshark-qt
  - apparmor
  - openssh
  - tpm2-tools
  - lynis

  # Miscellaneous
  - seatd
  - keyd
  - pciutils
  - gettext
  - kate
  # Audio & multimedia GUI
  - pavucontrol
  - pwvucontrol
  - easyeffects
  - qpwgraph

  # System monitoring & information
  - btop

  - firewalld
  - opensnitch
  # LLVM/Clang toolchain
  - llvm
  - clang
  - mold

  # Rust toolchain
  - rustup

  # Runtime environments
  - python
  - nodejs

  # Build systems
  - meson
  - cmake
  - binutils
  - samurai



  # Wayland & display
  - wayland
  - wayland-utils
  - wayland-protocols
  - wtype
  - wlr-randr
  - wev
  - wdisplays
  - kanshi

  # Miscellaneous system packages
  - biome
  - dbus-broker-units
  - dbus-broker
  - zlib-ng
  - libusb
  - vulkan-icd-loader
  - vulkan-headers
  - vulkan-tools
  - plymouth
  - mesa-tkg-git
  - lib32-mesa-tkg-git
  # System shells
  - nushell
  - zsh
  - fish
  - bash
  - ccache
  - sccache

  # Fonts
  - noto-fonts
  - terminus-font
  - inter-font

  # Vulkan graphics
  - vkd3d
  - vkbasalt

  # Intel graphics
  - libva
  - libva-utils
  - libvpl
  - libvpl-tools
  - intel-gpu-tools
  - intel-media-driver      # Modern VA-API (Broadwell+)
  - intel-compute-runtime   # OpenCL
  - opencl-headers
  - ocl-icd                 # OpenCL Installable Client Driver loader
  - vpl-gpu-rt              # Intel VPL
  - libva-intel-driver      # Legacy VA-API (Haswell & older)
  - intel-graphics-compiler # Compiler for OpenCL
  - lib32-libva
  - lib32-libva-intel-driver

  # XWayland
  - xorg-xwayland
  # Virtual camera and I2C tools
  - v4l2loopback-dkms
  - v4l2loopback-utils
  - i2c-tools
  - slibtool
  - unzip-zstd
  - lib32-libstdc++5
  - p7zip-full-bin
  - limine-booster
  - vulkan-extensionlayer-git
  - mimalloc
  - xwayland-satellite-git
  - btrfs-list
  - libzstd-seek-git
  - libvirt-venus
  - btrfs-desktop-notification
  - python-anyqt
  - xwayland-run-git
  - archlinux-userland-fs-cmp
  - python-zstandard
  - virtio-win
  - xwaylandvideobridge
  - python-indexed-zstd
  - tela-icon-theme-purple-git
  - btrfs-du
  - mkinitcpio-extras
  - pywal-spicetify
  - kernel-modules-hook-reflink
  - btrfs-compress
  - stevenblack
  - aurscan-git
  - qemu-ovmf-secureboot-git
  - zarchive-git
  - catppuccin-gtk-theme-mocha
  - jstest-gtk-git
  - cachyos-settings
  - bpftune-git
  - libmaddy
  - libnick
  - clamav-gui
  - python-pywal16
  - python-apscheduler
  - python-netifaces-plus
  - libstdc++5
  - libgl
  - bees-git
  - btdu-bin
  - plymouth-theme-arch-logo-symbol
  - zstd-git
  - sdl2
  - bdf
  - ntfsprogs-plus
  - libgendesktop
  - glib
  - t2sz
  - fuzzel-rbw
  - fresh-editor-bin
exclude:
  - nano
  - linux-lts
  - cachyos-plymouth-bootanimation
  - cat
  - ufw
