description: Base system packages
post_install_hook: ""
hooks_behavior: skip
packages:
  # Essential base system
  - base
  - base-devel
  # Firmware
  - intel-ucode
  - limine-entry-tool
  - limine-snapper-sync
  - linux-cachyos
  - linux-cachyos-headers
  - linux-firmware
  - linux-firmware-intel
  - xone-dkms
  - xone-dongle-firmware
  # dcli dependencies
  - fzf
  - irqbalance
  - paru
  - snapper
  - yay-bin
  # Theming
  - python-pywal16
  # Audio system packages
  - alsa-utils
  - blueman
  - bluez
  - bluez-tools
  - bluez-utils
  - cava
  - libsixel
  - noise-suppression-for-voice
  - pipewire
  - pipewire-alsa
  - pipewire-audio
  - pipewire-jack
  - pipewire-pulse
  - rnnoise
  - rtkit
  - wireplumber
  # Security & Network Base
  - firewalld
  - opensnitch
  # LLVM/Clang toolchain
  - clang
  - llvm
  - mold
  # Rust toolchain
  - rustup
  # Runtime environments
  - nodejs
  - python
  # Build systems
  - binutils
  - cmake
  - meson
  - samurai
  # File Management
  - nemo
  # Core CLI utilities
  - bat
  - brightnessctl
  - curl
  - eza
  - fd
  - imv
  - jaq
  - lvm2
  - nvtop
  - ripgrep
  - unzip
  - usbutils
  - wget
  # Utilities & compression
  - bind-tools
  - dosfstools
  - evtest
  - perl-file-mimeinfo
  - shared-mime-info
  - tealdeer
  - ueberzugpp
  - xdg-user-dirs
  - xdg-utils
  # System GUI applications
  - network-manager-applet
  - networkmanager
  - networkmanager-openvpn
  - nftables
  # Audio & multimedia GUI
  - easyeffects
  - pavucontrol
  - pwvucontrol
  - qpwgraph
  # System monitoring & information
  - btop
  # System utilities & tools
  - ffmpeg
  # File system tools
  - avfs
  - btrfs-assistant-git
  - btrfs-heatmap
  - btrfs-progs
  - compsize
  - disorderfs
  - duperemove
  - f2fs-tools
  - fuse2
  - fuse3
  - fuseiso
  - gvfs
  - libappimage
  - virtiofsd
  # Screenshot & recording
  - swappy
  # Network & security
  - apparmor
  - lynis
  - nmap
  - openssh
  - tpm2-tools
  - wireshark-qt
  # Miscellaneous
  - gettext
  - kate
  - keyd
  - pciutils
  - seatd
  # System monitoring & management
  - ananicy-cpp
  - busybox
  - cachyos-ananicy-rules
  - earlyoom
  - fwupd
  - gammastep
  - geoclue
  - lm_sensors
  - mkinitcpio
  - mkinitcpio-busybox
  - mkinitcpio-firmware
  - scx-scheds
  - thermald
  - tuned
  - upower
  - wlsunset
  # Wayland & display
  - kanshi
  - wayland
  - wayland-protocols
  - wayland-utils
  - wdisplays
  - wev
  - wlr-randr
  - wtype
  # Miscellaneous system packages
  - biome
  - dbus-broker
  - dbus-broker-units
  - lib32-mesa-tkg-git
  - libusb
  - mesa-tkg-git
  - plymouth
  - vulkan-headers
  - vulkan-icd-loader
  - vulkan-tools
  - zlib-ng
  # System shells
  - bash
  - ccache
  - fish
  - nushell
  - sccache
  - zsh
  # Fonts
  - inter-font
  - noto-fonts
  - terminus-font
  # Vulkan graphics
  - vkbasalt
  - vkd3d
  # Intel graphics
  - intel-compute-runtime
  - intel-graphics-compiler
  - intel-gpu-tools
  - intel-media-driver
  - lib32-libva
  - lib32-libva-intel-driver
  - libva
  - libva-intel-driver
  - libva-utils
  - libvpl
  - libvpl-tools
  - ocl-icd
  - opencl-headers
  - vpl-gpu-rt
  # XWayland
  - xorg-xwayland
  # Virtual camera and I2C tools
  - booster
  - i2c-tools
  - lib32-libstdc++5
  - p7zip-full-bin
  - slibtool
  - unzip-zstd
  - v4l2loopback-dkms
  - v4l2loopback-utils
  # Extended System & AUR
  - archlinux-userland-fs-cmp
  - aurscan-git
  - bees-git
  - bpftune-git
  - btdu-bin
  - btrfs-compress
  - btrfs-desktop-notification
  - btrfs-du
  - btrfs-list
  - btrfs-zstd-seek-git
  - cachyos-hooks
  - cachyos-settings
  - catppuccin-gtk-theme-mocha
  - clamav-gui
  - fresh-editor-bin
  - fuzzel-rbw
  - jstest-gtk-git
  - kernel-modules-hook-reflink
  - libgl
  - libmaddy
  - libnick
  - libstdc++5
  - libvirt-venus
  - mimalloc
  - mkinitcpio-extras
  - plymouth-theme-arch-logo-symbol
  - python-anyqt
  - python-apscheduler
  - python-indexed-zstd
  - python-netifaces-plus
  - python-zstandard
  - pywal-spicetify
  - qemu-ovmf-secureboot-git
  - sdl2
  - stevenblack
  - t2sz
  - tela-icon-theme-purple-git
  - virtio-win
  - vulkan-extensionlayer-git
  - xwayland-run-git
  - xwayland-satellite-git
  - xwaylandvideobridge
  - zarchive-git
  - zstd-git
  # CachyOS Specific
  - cachyos-hello
  - cachyos-kernel-manager
  - cachyos-packageinstaller
  # Networking
  - dhclient
  - dnsutils
  - ethtool
  - iwd
  - modemmanager
  - nsss-mdnss
  - usb_modeswitch
  - wireless-regdb
  - wpa_supplicant
  - xl2tpd
  # System Maintenance
  - accountsservice
  - bash-completion
  - bluez-hid2hci
  - bluez-libs
  - octopi
  - pacman-contrib
  - pkgfile
  - rebuild-detector
  - reflector
  # Multimedia Support
  - ffmpegthumbnailer
  - gst-libav
  - gst-plugin-pipewire
  - gst-plugins-bad
  - gst-plugins-ugly
  - libgsf
  - libopenraw
  - libvdcss
  - mlocate
  - poppler-glib
  - vlc-plugins-all
  # Hardare & Boot
  - alsa-firmware
  - alsa-plugins
  - cpupower
  - dmraid
  - efitools
  - freetype2
  - haveged
  - hdparm
  - hwdetect
  - lsscsi
  - mtools
  - noto-fonts-cjk
  - noto-fonts-emoji
  - ntp
  - power-profiles-daemon
  - sg3_utils
  - smartmontools
  - sof-firmware
  - unrar
exclude:
  - nano
  - linux-lts
  - cachyos-plymouth-bootanimation
  - cat
  - ufw