description: Base system packages
post_install_hook: ""
hooks_behavior: skip
packages:

  # Core system foundation
  - base # Minimal package set to define a basic Arch Linux installation (kernel, core utilities, package manager)
  - base-devel # Basic tools to build Arch Linux packages (make, autoconf, automake, etc.)

  
  # System utilities
  - irqbalance # IRQ balancing daemon for SMP systems to optimize interrupt distribution
  - snapper # Tool for managing BTRFS and LVM snapshots with rollback capabilities

  # Pacman enhancement tools
  - pacman-contrib # Contributed scripts and tools for pacman systems (pacman-color, checkupdates, etc.)
  - pkgfile # Tool to search for files in official repository packages (find which package provides a file)
  - rebuild-detector # Detects which packages need to be rebuilt after library updates
  - reflector # Python module and script to retrieve and filter the latest Pacman mirror list for optimal download speeds
  - extra-cmake-modules # Extra modules and scripts for CMake build system
  

  # File format and media libraries
  - ffmpegthumbnailer # Lightweight video thumbnailer that can be used by file managers
  - libgsf # Extensible I/O abstraction library for dealing with structured file formats (Office documents, archives)
  - libopenraw # Library for decoding RAW image files from digital cameras
  - poppler-glib # Poppler glib bindings for PDF rendering and manipulation
  - vlc-plugins-all # Free and open source cross-platform multimedia player and framework - all plugins included
  

  # Bootloader
  - limine # Advanced, portable, multiprotocol bootloader with modern features
  - limine-mkinitcpio-hook # Install kernel for the Limine bootloader (integration with Arch's initramfs system)
  
  # Filesystem utilities
  - btrfs-progs # Btrfs filesystem utilities for advanced copy-on-write filesystem
  - f2fs-tools # Tools for Flash-Friendly File System (F2FS) optimized for SSDs
  - fuse2 # Interface for userspace programs to export a filesystem to the Linux kernel (legacy version)
  - fuse3 # Interface for userspace programs to export a filesystem to the Linux kernel (modern version)
  - fuseiso # FUSE module to mount ISO filesystem images without root privileges
  - gvfs # Virtual filesystem implementation for GIO providing network and archive access
  - libappimage # Reference implementation of the AppImage specification for portable applications
  

  # CPU scheduling and thermal management
  - scx-scheds # sched_ext schedulers and tools for advanced CPU scheduling (BPF-based)
  - thermald # The Linux Thermal Daemon program from 01.org for thermal management
  - tuned # Daemon that performs monitoring and adaptive configuration of devices in the system
  - upower # Abstraction for enumerating power devices, listening to device events and querying history and statistics
  # Desktop notifications
  - fyi # A command line utility and notify-send alternative to send desktop notifications (desktop notification tool)
  - notify-send.sh # notify-send drop-in replacement with more features (enhanced notification tool)
  

  # CachyOS utilities
  - cachyos-hello # Welcome screen for CachyOS providing system information and setup guidance
  - cachyos-kernel-manager # Simple kernel manager for CachyOS with easy kernel switching
  - cachyos-packageinstaller # Simple Software Application Package Installer for CachyOS which helps setting up & installing applications
  

  # Archive utilities
  - unzip # For extracting and viewing files in .zip archives
  - dosfstools # DOS filesystem utilities for FAT16/FAT32 filesystems
  - evtest # Input device event monitor and query tool for debugging input devices
  - avfs # Virtual filesystem that allows browsing compressed files and archives transparently
  

exclude:
  - nano # Text editor (excluded in favor of other editors)
  - linux-lts # Long-term support kernel (excluded in favor of mainline)
  - cachyos-plymouth-bootanimation # Boot animation (excluded for performance)
  - cat # Basic command (already included in core)
  - ufw # Uncomplicated Firewall (excluded in favor of other firewall solutions)
