description: Base system packages
post_install_hook: ""
hooks_behavior: skip
packages:
  # Essential base system
  - base
  - base-devel
  # dcli dependencies
  - irqbalance
  - paru
  - snapper
  - yay-bin
  # Security & Network Base
  
  - pacman-contrib
  - pkgfile
  - rebuild-detector
  - reflector
  - extra-cmake-modules
  # Utilities & compression
  # System GUI applications
  # Network management
  # Audio & multimedia GUI
  # System monitoring & information
    # System Maintenance
 
  # Multimedia Support
  - ffmpegthumbnailer
  - libgsf
  - libopenraw
  - mlocate
  - poppler-glib
  - vlc-plugins-all
  - limine
  - limine-mkinitcpio-hook
  - btrfs-progs
  - f2fs-tools
  - fuse2
  - fuse3
  - fuseiso
  - gvfs
  - libappimage
  - ananicy-cpp
 
  - scx-scheds
  - thermald
  - tuned
  - upower
  - cachyos-hello
  - cachyos-kernel-manager
  - cachyos-packageinstaller
  - unzip
  # Utilities & compression
  - bind-tools
  - dosfstools
  - evtest
  # System utilities & tools
  # File system tools
  - avfs
exclude:
  - nano
  - linux-lts
  - cachyos-plymouth-bootanimation
  - cat
  - ufw
