description: Base system packages

# Use the flat syntax as seen in your other files.
# We point to the global 'scripts/' folder relative to where you run dcli (repo root).
post_install_hook: ""
hooks_behavior: skip
packages:
  # Essential base system
  - base
  - base-devel

  # Firmware
  - linux-firmware
  - linux-firmware-intel
  - intel-ucode
  - linux-cachyos
  - linux-cachyos-headers
  - xone-dongle-firmware
  - xone-dkms
  #- limine-mkinitcpio-hook
  #- limine-entry-tool
  - limine-snapper-sync

  # dcli dependencies
  - paru
  - yay-bin
  - fzf
  - snapper


  # Theming
  - python-pywal16

  # Audio system packages
  - pipewire
  - wireplumber
  - cava
  - libsixel
  - alsa-utils
  - bluez-tools
  - bluez
  - bluez-utils
  - pipewire-audio
  - pipewire-alsa
  - pipewire-pulse
  - pipewire-jack
  - rtkit
  - blueman
  - noise-suppression-for-voice
  - rnnoise

  - firewalld
  - opensnitch
  # LLVM/Clang toolchain
  - llvm
  - clang
  - mold

  # Rust toolchain
  - rustup

  # Runtime environments
  - python
  - nodejs

  # Build systems
  - meson
  - cmake
  - binutils
  - samurai
exclude:
  - nano
  - linux-lts
  - cachyos-plymouth-bootanimation
  - cat
  - ufw
