#!/bin/bash
set -e

echo "=== Installing AUR Packages ==="

# Function to check for commands
check_cmd() {
    if ! command -v "$1" &> /dev/null; then
        echo "Error: '$1' is not installed. Please install it first."
        exit 1
    fi
}

check_cmd paru

# List of AUR packages to install
aur_packages=(
    "appimagelauncher-git"
    "slibtool"
    "obs-advanced-masks"
    "proton-mail"
    "cbonsai"
    "obs-composite-blur"
    "bitwarden-menu-git"
    "obs-plugin-vertical-canvas-git"
    "obs-wayland-hotkeys-git"
    "davinci-ffmpeg-encoder-plugin"
    "krita-plugin-pythonplugindevelopertools-git"
    "libgen-cli-bin"
    "unzip-zstd"
    "lib32-libstdc++5"
    "podman-compose-git"
    "obs-shaderfilter-git"
    "opentabletdriver-git"
    "pipes.sh"
    "scream-git"
    "spicetify-themes-git"
    "audacity-openvino-bin"
    "p7zip-full-bin"
    "matugen-bin"
    "limine-booster"
    "vulkan-extensionlayer-git"
    "mimalloc"
    "blender-launcher-v2-bin"
    "xwayland-satellite-git"
    "btrfs-list"
    "obs-source-dock"
    "wine-tkg-staging-wow64-bin"
    "libzstd-seek-git"
    "libvirt-venus"
    "fresh-editor-bin"
    "btrfs-desktop-notification"
    "python-anyqt"
    "xwayland-run-git"
    "archlinux-userland-fs-cmp"
    "bottles"
    "heroic-games-launcher-git"
    "boxbuddy"
    "unzip-zstd"
    "python-zstandard"
    "bun-git"
    "virtio-win"
    "waydroidsu"
    "xwaylandvideobridge"
    "python-indexed-zstd"
    "proton-authenticator-bin"
    "carapace-bin"
    "tela-icon-theme-purple-git"
    "btrfs-du"
    "nodejs-inshellisense"
    "obs-noise"
    "mkinitcpio-extras"
    "pywal-spicetify"
    "kernel-modules-hook-reflink"
    "crystal-dock-bin"
    "btrfs-compress"
    "stevenblack"
    "aurscan-git"
    "qemu-ovmf-secureboot-git"
    "spicetify-extensions-rxri-git"
    "zarchive-git"
    "davinci-convert"
    "catppuccin-gtk-theme-mocha"
    "jstest-gtk-git"
    "obs-text-pthread"
    "dopamine-official"
    "obs-plugin-aitum-multistream-git"
    "mods-bin"
    "flang"
    "waydroid-helper-git"
    "libgendesktop"
    "qwen-code"
    "bibata-cursor-theme-bin"
    "spotify-dev"
    "obs-plugin-browser"
    "zen-browser-bitwarden"
    "zluda-git"
    "glib"
    "t2sz"
    "obs-move-transition"
    "obs-plugin-time-source"
    "catppuccin-obs-theme-git"
    "fuzzel-rbw"
    "libstdc++5"
    "libgl"
    "bees-git"
    "btdu-bin"
    "obs-plugin-input-overlay-bin"
    "spicetify-custom-apps-and-extensions-git"
    "waydroid-launcher-git"
    "plymouth-theme-arch-logo-symbol"
    "obs-pipewire-audio-capture-bin"
    "llvm-minimal-git"
    "cargo"
    "obs-source-switcher"
    "parabolic"
    "zstd-git"
    "sdl2"
    "bdf"
    "equibop-bin"
    "ntfsprogs-plus"
    "calibre-web"
    "obs-3d-effect"
    "cachyos-settings"  
    "bpftune-git"
    "libmaddy"
    "libnick"
    "clamav-gui"
    "python-pywal16"
    "libtorch-cxx11abi-cpu"
    "openvino-models"
    "python-apscheduler"
    "python-netifaces-plus"
    )

# Install packages using paru with --noconfirm
echo "Installing AUR packages using paru..."
paru -S "${aur_packages[@]}"

echo "AUR package installation complete."