#!/bin/bash

# ==============================================================================
# SPIDY NETWORK OPTIMIZATION SCRIPT
# Profile: <50 Mbps | Low RAM | Quad9 ECS + Cloudflare Fallback
# ==============================================================================

set -e # Exit immediately if a command fails

echo "=== 🕷️ Starting Spidy Network Optimization ==="

# 1. Install Necessary Packages
echo "[-] Installing PowerDNS Recursor, nftables, and tools..."
sudo pacman -S --needed --noconfirm powerdns-recursor nftables bind-tools

# ==============================================================================
# 2. DNS SETUP: PowerDNS with Quad9 ECS & Cloudflare
# ==============================================================================
echo "[-] Configuring PowerDNS Recursor..."

# Stop systemd-resolved to free port 53
sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved

# Backup existing config
sudo mv /etc/powerdns/recursor.conf /etc/powerdns/recursor.conf.bak 2>/dev/null || true

# Write Config
# Quad9 ECS IPs: 9.9.9.11, 149.112.112.11
# Cloudflare Fallback: 1.1.1.1
cat <<EOF | sudo tee /etc/powerdns/recursor.conf
# === PowerDNS Recursor Spidy Config ===
local-address=127.0.0.1
local-port=53
allow-from=127.0.0.0/8

# Performance & Caching
threads=2
pdns-distributes-queries=yes
max-cache-entries=500000
packetcache-ttl=3600

# Forwarding Strategy:
# 1. Quad9 ECS (Primary - Malware blocking + Location aware)
# 2. Cloudflare (Fallback - Speed)
# Syntax: forward-zones-recurse=.=IP1;IP2;IP3
forward-zones-recurse=.=9.9.9.11;149.112.112.11;1.1.1.1

# Security
dnssec=validate
socket-dir=/var/run/pdns-recursor
EOF

echo "[-] Configuring System Resolver..."
# Force system to use local PowerDNS
sudo rm -f /etc/resolv.conf/etc/re
cat <<EOF | sudo tee solv.conf
# Generated by Spidy Optimization Script
nameserver 127.0.0.1
options edns0 trust-ad
EOF

# Lock resolv.conf so NetworkManager can't break it
sudo chattr +i /etc/resolv.conf

echo "[-] Configuring NetworkManager to ignore DNS..."
sudo mkdir -p /etc/NetworkManager/conf.d
cat <<EOF | sudo tee /etc/NetworkManager/conf.d/00-spidy-dns.conf
[main]
dns=none
systemd-resolved=false
EOF

sudo systemctl restart NetworkManager
sudo systemctl enable --now pdns-recursor

# ==============================================================================
# 3. FIREWALL (nftables)
# ==============================================================================
echo "[-] Configuring nftables..."

cat <<EOF | sudo tee /etc/nftables.conf
#!/usr/sbin/nft -f
flush ruleset
table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        iifname "lo" accept
        ct state established,related accept
        iifname { "virbr0", "docker0", "podman0" } accept
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept
        tcp dport { 22, 80, 443, 8080, 59010, 59011 } accept
        udp dport { 59010, 59011 } accept
    }
    chain forward {
        type filter hook forward priority 0; policy drop;
    }
    chain output {
        type filter hook output priority 0; policy accept;
    }
}
EOF
sudo systemctl enable --now nftables

# ==============================================================================
# 4. KERNEL / SYSCTL TUNING (Target: <50Mbps / Spidy Profile)
# ==============================================================================
echo "[-] Applying Spidy Sysctl Optimizations..."

# Removing old config if exists
sudo rm -f /etc/sysctl.d/99-cachyos-net-opt.conf

cat <<EOF | sudo tee /etc/sysctl.d/99-spidy-net-opt.conf

# Default buffer sizes (~256KB)
net.core.rmem_default=262144
net.core.wmem_default=262144

# Max buffer sizes (~6MB) -
net.core.rmem_max=6291456
net.core.wmem_max=6291456

# Backlog and Budget
net.core.netdev_max_backlog=5000
net.core.netdev_budget=300

# Queue Discipline - CAKE is king for slow connections
net.core.default_qdisc=cake

# Security Flag (JIT Hardening)
net.core.bpf_jit_harden=1

# --- TCP Optimizations ---
# TCP Read/Write Buffers: Min / Default / Max
net.ipv4.tcp_rmem=4096 87380 6291456
net.ipv4.tcp_wmem=4096 65536 6291456

# --- Flags Preserved as requested ---
net.ipv4.tcp_low_latency=1
net.ipv4.tcp_no_metrics_save=1
net.ipv4.tcp_moderate_rcvbuf=1
net.ipv4.tcp_window_scaling=1
net.ipv4.tcp_timestamps=1
net.ipv4.tcp_sack=1
net.ipv4.tcp_fin_timeout=15
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_rfc1337=1
net.ipv4.tcp_syncookies=1

# Congestion Control
net.ipv4.tcp_congestion_control=bbr
net.ipv4.tcp_fastopen=3

# Misc
net.ipv4.tcp_mtu_probing=1
net.ipv4.ip_forward=0
net.ipv4.icmp_ignore_bogus_error_responses=1
net.ipv4.conf.default.rp_filter=1
net.ipv4.conf.all.rp_filter=1
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.default.accept_redirects=0
EOF

# Apply Sysctl
sudo sysctl --system

echo "=== 🕷️ Spidy Optimization Complete ==="
echo "1. Verify DNS: 'dig google.com' (Should show SERVER: 127.0.0.1)"
echo "2. Verify Quad9: 'dig +short txt locations.q9f.org' (Should verify Quad9 location)"