#!/bin/bash

# config_fish_setup.sh
# Generates a config.fish that wires up Starship, Zoxide, Fzf, Bat, Eza, etc.
# DOES NOT install packages.

# Configuration Paths
FISH_DIR="$HOME/.config/fish"
CONFIG_FILE="$FISH_DIR/config.fish"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}Configuring Fish Shell...${NC}"

# 1. Create directory if missing
mkdir -p "$FISH_DIR"

# 2. Backup existing config
if [ -f "$CONFIG_FILE" ]; then
    echo -e "${YELLOW}Backing up existing config to config.fish.bak${NC}"
    cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"
fi

# 3. Write the new configuration
echo -e "${GREEN}Writing new config.fish...${NC}"

cat > "$CONFIG_FILE" <<'EOF'
# -----------------------------------------------------------------------------
# Fish Config - Generated by Setup Script
# -----------------------------------------------------------------------------

# Remove the standard greeting
set -U fish_greeting

if status is-interactive

    # -------------------------------------------------------------------------
    # 1. INTEGRATIONS (Only run if tools are installed)
    # -------------------------------------------------------------------------

    # Starship (Prompt)
    if type -q starship
        starship init fish | source
    end

    # Carapace (Completions)
    if type -q carapace
        set -x CARAPACE_BRIDGES 'zsh,fish,bash,inshellisense' # Optional: extra bridges
        carapace _carapace | source
    end

    # Zoxide (Smarter cd)
    if type -q zoxide
        zoxide init fish | source
        alias cd='z'
    end

    # Fzf (Fuzzy Finder)
    if type -q fzf
        fzf --fish | source
        
        # Use 'fd' instead of 'find' for fzf (faster, respects .gitignore)
        if type -q fd
            set -gx FZF_DEFAULT_COMMAND "fd --type f"
            set -gx FZF_CTRL_T_COMMAND "$FZF_DEFAULT_COMMAND"
        end
    end

    # -------------------------------------------------------------------------
    # 2. ALIASES & REPLACEMENTS
    # -------------------------------------------------------------------------

    # Eza (Better ls)
    if type -q eza
        alias ls='eza --icons --group-directories-first'
        alias ll='eza -l --icons --group-directories-first'
        alias la='eza -la --icons --group-directories-first'
        alias tree='eza --tree --icons'
    end

    # Bat (Better cat)
    if type -q bat
        alias cat='bat'
        # Set a theme for bat (optional, 'Dracula' or 'TwoDark' are popular)
        set -gx BAT_THEME "base16" 
    end

    # Ripgrep (Better grep)
    if type -q rg
        alias grep='rg'
    end

    # Fd (Better find)
    if type -q fd
        alias find='fd'
    end

    # Btop (Better top)
    if type -q btop
        alias top='btop'
    end

    # Navigation
    alias ..='cd ..'
    alias ...='cd ../..'
    alias ....='cd ../../..'

    # Safety
    alias cp='cp -i'
    alias mv='mv -i'
    alias rm='rm -i'
    
    # System
    alias df='df -h'
    alias free='free -h'

    # -------------------------------------------------------------------------
    # 3. EDITOR (Helix)
    # -------------------------------------------------------------------------
    
    if type -q helix
        set -gx EDITOR helix
        set -gx VISUAL helix
        alias hx='helix'
        alias vim='helix'
        alias nano='helix'
    end

    # -------------------------------------------------------------------------
    # 4. ARCH LINUX PACKAGE MANAGEMENT (Abbreviations)
    # -------------------------------------------------------------------------
    
    # Expand these when you type space
    abbr -a pac 'sudo pacman'
    abbr -a paci 'sudo pacman -S'
    abbr -a pacr 'sudo pacman -Rns' # Remove package and unused deps
    abbr -a pacu 'sudo pacman -Syu' # Update
    abbr -a pacs 'pacman -Ss'       # Search
    abbr -a pacq 'pacman -Qi'       # Query info
    abbr -a unlock 'sudo rm /var/lib/pacman/db.lck'

end
EOF

echo -e "${GREEN}[✔] Configuration written successfully!${NC}"
echo -e "${BLUE}Restart your shell or run 'source ~/.config/fish/config.fish' to apply.${NC}"