#!/bin/bash

echo "=== Configuring XDG Defaults & Directories (Customized for Don) ==="

# ==============================================================================
# 0. CONFIGURATION (Auto-detected from your package list)
# ==============================================================================
# Browser: Zen is your primary, Helium/Chromium as backups
BROWSER="zen.desktop"

# Images: IMV is installed and excellent for tiling WMs
IMG_VIEWER="imv.desktop"

# Video/Audio: MPV is installed and handles everything
VID_PLAYER="mpv.desktop"
AUD_PLAYER="mpv.desktop"

# Editor: Kate is installed
EDITOR="org.kde.kate.desktop"

# File Manager: Nemo is your main FM
FILE_MGR="nemo.desktop"

# PDF: No dedicated reader found (Papers/Okular), defaulting to Zen
PDF_VIEWER="zen.desktop"

# ==============================================================================
# 1. XDG USER DIRECTORIES
# Matches xdg.userDirs
# ==============================================================================
echo "Updating User Directories..."

# 1. Ensure basic folders exist
xdg-user-dirs-update

# 2. Configure Screenshots Directory
# Niri config saves to: ~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png
USER_DIRS="$HOME/.config/user-dirs.dirs"
SCREENSHOT_DIR="$HOME/Pictures/Screenshots"

# Create the physical folder
mkdir -p "$SCREENSHOT_DIR"

# Update config if not already set
if [ -f "$USER_DIRS" ]; then
    if ! grep -q "XDG_SCREENSHOTS_DIR" "$USER_DIRS"; then
        echo "Adding XDG_SCREENSHOTS_DIR..."
        echo "XDG_SCREENSHOTS_DIR=\"$SCREENSHOT_DIR\"" >> "$USER_DIRS"
    fi
fi

# ==============================================================================
# 2. DEFAULT APPLICATIONS (MIMEAPPS.LIST)
# Matches xdg.mimeApps.defaultApplications
# ==============================================================================
echo "Generating mimeapps.list..."

MIME_FILE="$HOME/.config/mimeapps.list"

# Backup existing file if it exists
if [ -f "$MIME_FILE" ]; then
    echo "Backing up existing mimeapps.list to mimeapps.list.bak..."
    cp "$MIME_FILE" "$MIME_FILE.bak"
fi

# Generate new config
cat <<EOF > "$MIME_FILE"
[Default Applications]
# --- Web Browsing ---
text/html=$BROWSER
x-scheme-handler/http=$BROWSER
x-scheme-handler/https=$BROWSER
x-scheme-handler/ftp=$BROWSER
x-scheme-handler/about=$BROWSER
x-scheme-handler/unknown=$BROWSER
application/x-extension-htm=$BROWSER
application/x-extension-html=$BROWSER
application/x-extension-shtml=$BROWSER
application/xhtml+xml=$BROWSER
application/x-extension-xhtml=$BROWSER
application/x-extension-xht=$BROWSER

# --- Images (IMV) ---
image/jpeg=$IMG_VIEWER
image/png=$IMG_VIEWER
image/gif=$IMG_VIEWER
image/webp=$IMG_VIEWER
image/tiff=$IMG_VIEWER
image/x-icon=$IMG_VIEWER
image/svg+xml=$IMG_VIEWER
image/avif=$IMG_VIEWER
image/heic=$IMG_VIEWER
image/heif=$IMG_VIEWER
image/bmp=$IMG_VIEWER

# --- Video (MPV) ---
video/mp4=$VID_PLAYER
video/x-matroska=$VID_PLAYER
video/webm=$VID_PLAYER
video/quicktime=$VID_PLAYER
video/x-msvideo=$VID_PLAYER
video/x-flv=$VID_PLAYER
video/x-ms-wmv=$VID_PLAYER
video/mpeg=$VID_PLAYER
video/3gpp=$VID_PLAYER
video/mp2t=$VID_PLAYER

# --- Audio (MPV) ---
audio/mpeg=$AUD_PLAYER
audio/flac=$AUD_PLAYER
audio/x-wav=$AUD_PLAYER
audio/aac=$AUD_PLAYER
audio/ogg=$AUD_PLAYER
audio/opus=$AUD_PLAYER
audio/mp4=$AUD_PLAYER
audio/x-m4a=$AUD_PLAYER
audio/x-aiff=$AUD_PLAYER
audio/x-ape=$AUD_PLAYER

# --- Text / Code (Kate) ---
text/plain=$EDITOR
text/markdown=$EDITOR
text/x-python=$EDITOR
text/x-shellscript=$EDITOR
text/css=$EDITOR
text/x-c=$EDITOR
text/x-c++=$EDITOR
text/x-rust=$EDITOR
application/json=$EDITOR
application/xml=$EDITOR
application/javascript=$EDITOR
application/x-shellscript=$EDITOR
# Fallback for generic text
text/data=$EDITOR

# --- Archives / Files (Nemo) ---
application/zip=$FILE_MGR
application/x-7z-compressed=$FILE_MGR
application/x-rar-compressed=$FILE_MGR
application/x-tar=$FILE_MGR
application/gzip=$FILE_MGR
inode/directory=$FILE_MGR

# --- PDF (Zen Browser) ---
application/pdf=$PDF_VIEWER

# --- Misc ---
x-scheme-handler/chrome=zen.desktop
x-scheme-handler/mailto=proton-mail.desktop
EOF

# ==============================================================================
# 3. TERMINAL EMULATOR WRAPPER
# Matches xdg-terminal-exec
# ==============================================================================
echo "Configuring xdg-terminal-exec..."

BIN_DIR="$HOME/.local/bin"
WRAPPER="$BIN_DIR/xdg-terminal-exec"

mkdir -p "$BIN_DIR"

# Prioritizes Ghostty, then Kitty (Matches your installed packages)
cat <<EOF > "$WRAPPER"
#!/bin/sh
# Generated by dcli setup_xdg.sh
# Priority: Ghostty -> Kitty -> Alacritty -> Gnome Terminal

if command -v ghostty >/dev/null 2>&1; then
    exec ghostty "\$@"
elif command -v kitty >/dev/null 2>&1; then
    exec kitty "\$@"
elif command -v alacritty >/dev/null 2>&1; then
    exec alacritty "\$@"
else
    # Fallback
    echo "No preferred terminal found, trying x-terminal-emulator..." >&2
    exec x-terminal-emulator "\$@"
fi
EOF

chmod +x "$WRAPPER"

echo "XDG configuration applied successfully."
echo "Default Apps: Zen, Nemo, Kate, MPV, IMV."
