#!/bin/bash

# setup_fish.sh
# Automated Fish Shell Setup for Arch Linux
# Includes: Fish, Eza, Bat, Ripgrep, Fd, Btop, Helix
# Optional: Starship, Carapace

set -e # Exit immediately if a command exits with a non-zero status

# Colors for formatting
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}#################################################${NC}"
echo -e "${BLUE}#      Arch Linux Fish Setup Installer          #${NC}"
echo -e "${BLUE}#################################################${NC}"

# --- Check for Sudo ---
if [ "$EUID" -eq 0 ]; then 
  echo -e "${YELLOW}Please do not run as root. Run as a normal user with sudo privileges.${NC}"
  exit
fi

# --- Prompts for Optionals ---
read -p "Do you want to install Starship (Prompt)? [y/N] " install_starship
read -p "Do you want to install Carapace (Completions)? [y/N] " install_carapace
read -p "Do you want to set Fish as your default shell? [y/N] " set_default_shell

# --- Package Installation ---
echo -e "\n${GREEN}[+] Updating system and installing base tools...${NC}"
sudo pacman -Syu --noconfirm

# Base tools from your request
PACKAGES="fish eza bat ripgrep fd btop helix"

# Add optionals to package list
if [[ "$install_starship" =~ ^[Yy]$ ]]; then
    PACKAGES="$PACKAGES starship"
fi

if [[ "$install_carapace" =~ ^[Yy]$ ]]; then
    PACKAGES="$PACKAGES carapace"
fi

echo -e "${GREEN}[+] Installing packages: $PACKAGES${NC}"
sudo pacman -S --needed --noconfirm $PACKAGES

# --- Configuration Setup ---
FISH_CONFIG_DIR="$HOME/.config/fish"
FISH_CONFIG_FILE="$FISH_CONFIG_DIR/config.fish"

echo -e "\n${GREEN}[+] Configuring Fish...${NC}"

# Backup existing config
if [ -f "$FISH_CONFIG_FILE" ]; then
    echo -e "${YELLOW}Backing up existing config to config.fish.bak${NC}"
    cp "$FISH_CONFIG_FILE" "${FISH_CONFIG_FILE}.bak"
fi

mkdir -p "$FISH_CONFIG_DIR"

# Write Config Content
cat > "$FISH_CONFIG_FILE" <<EOF
# config.fish - Generated by setup script

# --- Interactive Session Checks ---
if status is-interactive
    # Commands to run in interactive sessions can go here
EOF

# Append Starship init if requested
if [[ "$install_starship" =~ ^[Yy]$ ]]; then
    echo "    starship init fish | source" >> "$FISH_CONFIG_FILE"
fi

# Append Carapace init if requested
if [[ "$install_carapace" =~ ^[Yy]$ ]]; then
    echo "    carapace _carapace | source" >> "$FISH_CONFIG_FILE"
fi

# Append User Aliases and settings
cat >> "$FISH_CONFIG_FILE" <<EOF

    # --- Navigation ---
    alias ..='cd ..'
    alias ...='cd ../..'
    alias ....='cd ../../..'

    # --- Eza (Better ls) ---
    alias ls='eza --icons --group-directories-first'
    alias ll='eza -l --icons --group-directories-first'
    alias la='eza -la --icons --group-directories-first'
    alias tree='eza --tree --icons'

    # --- Tools ---
    alias cat='bat'
    alias grep='rg'
    alias find='fd'
    alias top='btop'
    alias df='df -h'
    alias free='free -h'

    # --- Editor ---
    # Set Helix as default editor env vars
    set -gx EDITOR helix
    set -gx VISUAL helix
    
    alias hx='helix'
    alias vim='helix'
    alias nano='helix'

    # --- Safety ---
    alias cp='cp -i'
    alias mv='mv -i'
    alias rm='rm -i'

    # --- Package Management (Arch Abbrs) ---
    abbr -a pac 'sudo pacman'
    abbr -a paci 'sudo pacman -S'
    abbr -a pacr 'sudo pacman -Rns'
    abbr -a pacu 'sudo pacman -Syu'
    abbr -a pacs 'pacman -Ss'
    abbr -a pacq 'pacman -Qi'
    abbr -a unlock 'sudo rm /var/lib/pacman/db.lck'

    # Remove the standard greeting
    set -U fish_greeting
end
EOF

echo -e "${GREEN}[+] config.fish created successfully.${NC}"

# --- Set Default Shell ---
if [[ "$set_default_shell" =~ ^[Yy]$ ]]; then
    echo -e "\n${GREEN}[+] Changing default shell to Fish...${NC}"
    # Check if fish is in /etc/shells, if not add it (rare on Arch but good safety)
    if ! grep -q "$(which fish)" /etc/shells; then
        echo "Adding fish to /etc/shells"
        which fish | sudo tee -a /etc/shells
    fi
    chsh -s "$(which fish)"
    echo -e "${BLUE}Default shell changed. Please log out and back in for changes to take effect.${NC}"
else
    echo -e "${YELLOW}Skipping default shell change.${NC}"
    echo -e "You can try fish by typing: ${BLUE}fish${NC}"
fi

echo -e "\n${GREEN}[✔] Setup Complete!${NC}"